### ISSUE TITLE
navbar items show ontop of drawer

### ISSUE THREAD

**Issue by TheWithz** [tunitowen/fancy_bottom_navigation#8] opened 2019-01-10 22:07 UTC
Screen shot taken of the example app, with the only addition being `drawer: Drawer(),` to the scaffold. BottomNavBar items show on-top of the drawer when the drawer is in the open position. 

![screenshot 2019-01-10 at 17 03 31](https://user-images.githubusercontent.com/8269545/50999965-b229b200-14f9-11e9-9314-d7992b9171d8.png)

**Comment by TheWithz** [comment] 2019-01-10 22:19
To fix this, Am I supposed to pass the RouteObserver to the drawer as well?

**Comment by tunitowen** [comment] 2019-01-11 06:49
Never thought about that. The circle is an Overlay so draws on top of everything. I'll take a look soon

**Comment by tunitowen** [comment] 2019-01-11 11:35
This and other problems are being caused by the use of the Overlay widget, I think I have found a way to refactor this away. Will update later today.

**Comment by TonyOwenSky** [comment] 2019-01-11 13:36
Overlay widget has been removed, added a drawer to the example, and working fine now. Closing issue.

**Comment by tunitowen** [comment] 2019-01-11 13:37
v0.3.0 - Removed Overlay widget, added a Drawer to the example. Now working as expected.
Closing issue

**Closed by tunitowen** 2019-01-11 13:37 UTC
Labels: bug
